project:
  type: website

website:
  title: "Tobias Anton"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: skillcheck.qmd
        text: Playground

format:
  html:
    theme:
      light: darkly
      dark: darkly
    css: styles.css
    toc: true
    smooth-scroll: true
    html-math-method: katex
    link-external-newwindow: true

editor: visual
